### ISSUE TITLE
2 Errors on Staging Branch

### ISSUE THREAD

**Issue by suerion** [WheteThunger/AutomatedWorkcarts#5]
Hey, we had worked yet with Staging Branch,

if it would be added in release State ->
TryFindTrackNearby was Changed to TryFindTrackNear in Facepunch Staging Branch we had changed it

1468 ->`if (!TrainTrackSpline.TryFindTrackNear(hitPosition, 5, out spline, out distanceResult))`
2327-> `if (TrainTrackSpline.TryFindTrackNear(WorldPosition, 2, out spline, out distanceOnSpline))`

isEngine does not exist anymore in Staging, we had changed it to
1540 -> `if (trainCar.CarType != TrainCar.TrainCarType.Engine)`

I would come back after testing and debuging, if any errors come on the server

**Comment by suerion** [comment]
Our second admin has said, since it has changed to Near and not Nearby, it works not smooth anymore. Plugin worked yet.
 
 The WagonPrefab wagonD doesn‘t exist anymore we deleted the line

**Comment by WheteThunger** [comment]
I am aware of the errors, and I made fixes for them earlier this week, though I had not pushed them since sometimes it can cause issues with the GitHub integration on the uMod website. Since you created this issue, I have pushed the changes now to the develop branch.

https://github.com/WheteThunger/AutomatedWorkcarts/compare/master...develop

**Comment by suerion** [comment]
> I am aware of the errors, and I made fixes for them earlier this week, though I had not pushed them since sometimes it can cause issues with the GitHub integration on the uMod website. Since you created this issue, I have pushed the changes now to the develop branch.
> 
> [master...develop](https://github.com/WheteThunger/AutomatedWorkcarts/compare/master...develop)

Hey, no Problem, i thougt, you had a lot of work on Oxide, we would help if you don't had time to look on it. Thanks for your answere :)

**Comment by WheteThunger** [comment]
No worries. Thanks for looking out.

> it works not smooth anymore

Are you saying there are still issues, or all is good?

**Comment by suerion** [comment]
Hey, it is working, but the triggers are working not so good anymore

if i will change an trigger, it change an trigger in the near, not the right one, (2 triggers on sided rail) sometimes it use the false trigger. a little bit unsmooth.

Is there a way to change the rotation of the last train? it looks in the false direction
![20220804204043_1](https://user-images.githubusercontent.com/55131959/182929297-c8ca86ad-f5ea-4824-bafb-83c17a4dd232.jpg)

**Comment by WheteThunger** [comment]
To change the spawn rotation of a trigger, face the approximate direction you want the train to look, while aiming at the trigger, run `awt.rotate`, then `awt.respawn`.

> if i will change an trigger, it change an trigger in the near, not the right one, (2 triggers on sided rail) sometimes it use the false trigger. a little bit unsmooth.

Can you record a video, or take a screenshot of two triggers, and tell me which trigger was changed?

**Comment by suerion** [comment]
> To change the spawn rotation of a trigger, face the approximate direction you want the train to look, while aiming at the trigger, run `awt.rotate`, then `awt.respawn`.
> 
the problem is, we had only one trigger, and the second workcart looks in the false direction.
on the screenshot, you could see, the left one looks in the correct direction, but the right workcart looks in the same direction. is there a way to add an rotation on wagons and added workcarts?

>Can you record a video? Alternatively, take a screenshot of two triggers, while standing/flying in the original position where you ran the command, while aiming the original direction you were aiming when you ran the command, then tell me which trigger in the screenshot was changed. My guess is that there is an invisible collider which the raycast is hitting, which is closer to you, so it's finding the nearby trigger instead of the one you are aiming at.
>
we will come back with an video

**Comment by WheteThunger** [comment]
Ok, I see what you mean about the rear workcart facing forward. This is how the plugin is currently designed; all train cars face the same direction.

I have thought about ways to allow controlling the rotation, such as by giving them different names like WorkcartCovered_R ("_R" for reverse). Alternatively, the plugin could try to guess which direction you want the workcart to face. I'm not sure which of these approaches is better, but I think we'll have to pick one. Let me know if you have any suggestions.

**Comment by suerion** [comment]
On our side, i think the fastest way is an request, if two entites of workcarts are in the trigger, the second one should be added bidirectional to the spawn workcart,

Or You could also  add an request in the trigger, if the train will drive forward and backwards, it could be spawn the second worcart bidirectional.


this are 2 suggestions, ii think, this xcould be a way to go

**Comment by WheteThunger** [comment]
I've pushed a change to the `develop` branch which I think will resolve the issue where the commands find the wrong trigger.

I also experimented with allowing spawning of train cars backwards, by appending `_R` to the train car name. I've pushed that change to the `reverse-wagons` branch, but it has some bugs I haven't had time to figure out.

**Comment by suerion** [comment]
okey, we will look on debug server, if we found some changes, i will come back
